require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'RNBanubaModule' do
  use_unimodules!
    config = use_native_modules!

  use_react_native!(:path => '../node_modules/react-native/')
  
  pod 'BanubaARCloudSDK', '1.0.16'
  pod 'BanubaVideoEditorSDK', '1.0.16.1'
  pod 'BanubaAudioBrowserSDK', '1.0.16.1'
  pod 'BanubaMusicEditorSDK', '1.0.16'
  pod 'BanubaOverlayEditorSDK', '1.0.16'
  pod 'BanubaEffectPlayer', '1.0.15'
  pod 'BanubaSDK', '1.0.16'
  pod 'BanubaSDKSimple', '1.0.16'
  pod 'BanubaSDKServicing', '1.0.16'
  pod 'VideoEditor', '1.0.16'
  pod 'BanubaUtilities', '1.0.16'
  pod 'BanubaVideoGallerySDK', '1.0.16'
  pod 'BanubaLicenseServicingSDK', '1.0.16'
  pod 'BanubaTokenStorageSDK', '1.0.16.3'
  pod 'lottie-ios', "3.1.8"
end
