require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

source 'https://github.com/Banuba/specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'
use_frameworks!

target 'RNBanubaModule' do
  use_unimodules!
    config = use_native_modules!

  use_react_native!(:path => '../node_modules/react-native/')
    
  pod 'BanubaARCloudSDK', '0.0.14'
  pod 'BanubaVideoEditorSDK', '0.0.14.2'
  pod 'BanubaAudioBrowserSDK', '0.0.14'
  pod 'BanubaMusicEditorSDK', '0.0.14.2'
  pod 'BanubaOverlayEditorSDK', '0.0.14'
  pod 'BanubaEffectPlayer', '0.0.10'
  pod 'BanubaSDK', '0.0.14.2'
  pod 'VideoEditor', '0.0.14'
  pod 'lottie-ios', "3.1.8"
end
